// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayToy.Models;

namespace PlayToy.Migrations
{
    [DbContext(typeof(JugueteriaContext))]
    [Migration("20191102052552_playtoy")]
    partial class playtoy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PlayToy.Models.Juguete", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria");

                    b.Property<string>("Foto");

                    b.Property<string>("Nombre");

                    b.Property<decimal>("Precio");

                    b.HasKey("ID");

                    b.ToTable("Juguetes");
                });

            modelBuilder.Entity("PlayToy.Models.Pedido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("IDJuguete");

                    b.Property<int?>("IDUsuario");

                    b.Property<int?>("JugueteID");

                    b.Property<int?>("UsuarioId");

                    b.Property<DateTime>("fecha");

                    b.HasKey("ID");

                    b.HasIndex("JugueteID");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("PlayToy.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApeMat");

                    b.Property<string>("ApePat");

                    b.Property<string>("Contrasena");

                    b.Property<string>("Correo");

                    b.Property<DateTime>("FecNac");

                    b.Property<string>("Nombre");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PlayToy.Models.Pedido", b =>
                {
                    b.HasOne("PlayToy.Models.Juguete", "Juguete")
                        .WithMany("Pedidos")
                        .HasForeignKey("JugueteID");

                    b.HasOne("PlayToy.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
